In [8]:
'''vertical and horizontal - vstack and hstack
code to take two arrays a and b integrate a and b vertically annd horizontally'''
import numpy as np
a=list(map(int,input("Enter 3 numbers for array a,space seperated: ").split()))
b=list(map(int,input("Enter 3 numbers for array b,space seperated: ").split()))
a=np.array(a)
b=np.array(b)
v=np.vstack((a,b))
print("Vertical stack: \n",np.vstack((a,b)))
print("Horizontal stack: \n",np.hstack((a,b)))
print("Element 5 access",v[1,1])
print("Element 5 access",v[1][1])

Vertical stack: 
 [[3 4 5]
 [5 6 7]]
Horizontal stack: 
 [3 4 5 5 6 7]
Element 5 access 6
Element 5 access 6


In [3]:
'''code to extract all the odd numbers from user input
and print them in a list using array of numpy
input:1 2 3 4 5 9 8 7 6
outputt:[1,3,5,9,7]
'''
import numpy as np
a=input("Enter the array you wantt by giving spaces:")
arr=np.array(list(map(int,a.split())))
odd_numbers=arr[arr%2==1]
print("Odd numbers list: ",odd_numbers)

Odd numbers list:  [5 7]


In [11]:
'''
input:1 2 3 4 5
outputt:[-1,2,-1,4,-1]
'''
import numpy as np
a=input("Enter the array you wantt by giving spaces:")
arr=np.array(list(map(int,a.split())))
arr[arr%2==1]=-1
print("Odd numbers list: ",arr)

Odd numbers list:  [-1  4 -1  6 -1  8]


In [26]:
'''
input:1 2 3 4 5
outputt:[True,2,True,4,True]
'''
import numpy as np
data=input("Enter numbers seperated by spaces: ")
arr=np.array(list(map(int,data.split())),dtype=object)
mask=arr%3==0
print(mask)

[False False  True False False  True False False False  True False]


In [29]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("Element at[0,1]:",arr[0,1])
print("Frist row",arr[0,:])
print("First row:",arr[:,1:])
arr[0,0]=100
print("modify:",arr)

Element at[0,1]: 2
Frist row [1 2 3]
First row: [[2 3]
 [5 6]]
modify: [[100   2   3]
 [  4   5   6]]


In [30]:
#NaN
import numpy
arr=np.array([1,2,3,np.nan,5])
print("Mean inoring NaN:",np.nanmean(arr))
print("sum:",np.sum(arr))
#sqrt1.N Ei=1 to N(x~i=u)**2
print("std Ignoing NaN:",np.std(arr[~np.isnan(arr)]))

Mean inoring NaN: 2.75
sum: nan
std Ignoing NaN: 1.479019945774904


In [1]:
#replace NaN
import numpy as np
arr=np.array([1,np.nan,3,4,5])
n=np.where(np.isnan(arr),0,arr)
print(n)

[1. 0. 3. 4. 5.]


In [17]:
#universal functions ufuncs()
import numpy as np
a1=np.array([1.5,2.9,9.8])
print(a1.astype(np.int32))
a2=np.array([1,2,3,4])
print(a2.astype(np.float64))
a3=np.array([1.5,2.9,9.8])
print(a3.astype(str))
a4=np.array([0,1,7,0])
print(a4.astype(bool))
a5=np.array([True,True,False,True])
print(a5.astype(np.int32))
a6=np.array([1.5,2.9,9.8])
print(a6.astype(np.complex128))
a7=np.array([1,2,3,4])
print(a7.astype(np.int8))
a8=np.array([20250802,20050204])
print(a8.astype(datatime64[D]))


[1 2 9]
[1. 2. 3. 4.]
['1.5' '2.9' '9.8']
[False  True  True False]
[1 1 0 1]
[1.5+0.j 2.9+0.j 9.8+0.j]
[1 2 3 4]


NameError: name 'datatime64' is not defined