In [2]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print("Addition:",a+b)
print("product:",a*b)
print("Square:",a**2)
print("sin values",np.sin(a))

Addition: [ 6  8 10 12]
product: [ 5 12 21 32]
Square: [ 1  4  9 16]
sin values [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [39]:
import numpy as np
a=np.arange(1,10)
print(a)
reshaped=a.reshape((3,3))
print(reshaped)
linear=reshaped.reshape(-1)
print(linear)
print("greater than 5:",linear[linear>5])

print("Random numbers between 0 to 3: ",np.random.rand(3))
print("Random integer: \n",np.random.randint(1,100),(2,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
greater than 5: [6 7 8 9]
Random numbers between 0 to 3:  [0.42715257 0.68323237 0.33799975]
Random integer: 
 94 (2, 3)


In [45]:
'''code to print a 3x3 matrix which were filled with boolean value True using numpy'''
import numpy as np
a=np.full((3,3),True)
print(a)

b=np.full((4,4),'*')
print(b)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[['*' '*' '*' '*']
 ['*' '*' '*' '*']
 ['*' '*' '*' '*']
 ['*' '*' '*' '*']]
