In [1]:
print("hello")

hello


In [3]:
import numpy as np
x=np.array([1,2,3,4,5])
print("Array 1-D",x)
y=np.array([[1,2],[3,4]])
print("Array 2-D \n",y)

Array 1-D [1 2 3 4 5]
Array 2-D 
 [[1 2]
 [3 4]]


In [4]:
o=np.ones((3,6))
print("ones \n",o)

ones 
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [7]:
r=np.arange(0,11,2)
print("Array: ",r)

Array:  [ 0  2  4  6  8 10]


In [9]:
i=np.eye(8)
print("Identical coordinates: \n",i)

Identical coordinates: 
 [[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [11]:
seperate=np.linspace(0,1,5)
print("linespace",seperate)

linespace [0.   0.25 0.5  0.75 1.  ]
